[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
flexi_logger = "0.20"
itertools = "0.10"
log = "0.4"
thiserror = "1"
